CREATE TABLE IF NOT EXISTS lb_realtime_batches (
  checkpoint_key VARCHAR(255) NOT NULL,
  batch_id BIGINT NOT NULL,
  processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (checkpoint_key, batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lb_realtime_window_metrics (
  window_start DATETIME NOT NULL,
  window_end DATETIME NOT NULL,
  pv BIGINT NOT NULL DEFAULT 0,
  fav_cnt BIGINT NOT NULL DEFAULT 0,
  cart_cnt BIGINT NOT NULL DEFAULT 0,
  buy_cnt BIGINT NOT NULL DEFAULT 0,
  alert_type VARCHAR(32) NOT NULL DEFAULT 'normal',
  alert_message VARCHAR(255) NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (window_start)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lb_realtime_blog_metrics (
  window_start DATETIME NOT NULL,
  window_label VARCHAR(32) NOT NULL,
  pv BIGINT NOT NULL DEFAULT 0,
  fav_cnt BIGINT NOT NULL DEFAULT 0,
  cart_cnt BIGINT NOT NULL DEFAULT 0,
  buy_cnt BIGINT NOT NULL DEFAULT 0,
  alert_level INT NOT NULL DEFAULT 0,
  alert_type VARCHAR(32) NOT NULL DEFAULT 'normal',
  alert_message VARCHAR(255) NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (window_start)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
